apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 2-host-path
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
