apiVersion: v1
kind: PersistentVolume
metadata:
  name: 3-local
spec:
  storageClassName: "local-ssd"
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /var/log
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - "linux"

# https://kubernetes.io/docs/concepts/storage/volumes/#local
