apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 3-local
spec:
  storageClassName: "local-ssd"
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
