apiVersion: batch/v1
kind: Job
metadata:
  name: job-high-priority
spec:
  parallelism: 1 # 默认就是1，可以省略
  completions: 1 # 默认就是1，可以省略
  template:
    spec:
      priorityClassName: high-priority
      containers:
        - name: calc
          image: busybox
          command:
            - sh
            - -c
            - 'while true; do echo "high-priority: wake up"; sleep 1; done'
          resources:
            limits:
              cpu: "3"
      restartPolicy: Never
