# 应用部署 kubectl create -f 10-1.kuard-deployment.yaml。比较奇怪，这里用的是 create 而不是 apply。第一次用 create，后续用 apply。
# 缩放部署 kubectl scale deployments kuard --replicas=2，不要缩放 rs，因为 rs 被 deployment 管理，会自动被治愈
# kubectl describe deployments kuard 查看描述
# 查看部署历史
# kubectl rollout history deployment kuard
# deployment.apps/kuard 
# REVISION  CHANGE-CAUSE
# 1         <none>
# 2         Update to green kuard
# 查看当前部署的状态
# kubectl rollout status deployment kuard
# deployment "kuard" successfully rolled out
# 缩放部署只需改 replicas: 1 再 apply 即可，比较简单
# upgrade部署则需改其他并且加 annotations 再 apply

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
spec:
  selector:
    matchLabels:
      run: kuard
  replicas: 3
  template:
    metadata:
      labels:
        run: kuard
      annotations:
        kubernetes.io/change-cause: "Update to green kuard"
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:green
          imagePullPolicy: Always
