# 通过link完成的映射，应该是为了方便更新数据
# /config $ ls -al
# total 12
# drwxrwxrwx    3 root     root          4096 Mar 14 07:09 .
# drwxr-xr-x    1 root     root          4096 Mar 14 07:09 ..
# drwxr-xr-x    2 root     root          4096 Mar 14 07:09 ..2021_03_14_07_09_06.196326216
# lrwxrwxrwx    1 root     root            31 Mar 14 07:09 ..data -> ..2021_03_14_07_09_06.196326216
# lrwxrwxrwx    1 root     root            25 Mar 14 07:09 13-1.my-config.txt -> ..data/13-1.my-config.txt
# lrwxrwxrwx    1 root     root            20 Mar 14 07:09 another-param -> ..data/another-param
# lrwxrwxrwx    1 root     root            18 Mar 14 07:09 extra-param -> ..data/extra-param
# 查看 configmap object 的内容
# kubectl get configmap my-config -o yaml # ConfigMap data values are simple UTF-8 text specified directly in the manifest
# apiVersion: v1
# data:
#   13-1.my-config.txt: |
#     # kubectl create configmap my-config \
#     # --from-file=my-config.txt \
#     # --from-literal=extra-param=extra-value \
#     # --from-literal=another-param=another-value
#     # This is a sample config file that I might use to configure an application
#     parameter1 = value1
#     parameter2 = value2
#   another-param: another-value
#   extra-param: extra-value
# kind: ConfigMap
# 更新 configmap
# kubectl edit configmap my-config #直接修改了 object。查看发现只有文件系统内的文件有更新，环境变量、命令行参数并不会触发变更

apiVersion: v1
kind: Pod
metadata:
  name: kuard-config
spec:
  containers:
    - name: test-container
      image: gcr.io/kuar-demo/kuard-amd64:blue
      imagePullPolicy: Always
      command:
        - "/kuard"
        - "$(EXTRA_PARAM)"
      env:
        - name: ANOTHER_PARAM
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: another-param
        - name: EXTRA_PARAM
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: extra-param
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: my-config
  restartPolicy: Never
