# 创建 secret
# kubectl create secret generic kuard-tls \
# --from-file=kuard.crt \
# --from-file=kuard.key
# 应用 pod
# kubectl apply -f 13-3.kuard-secret.yaml
# 转发查看效果 注意 container port 已经改为 8443
# kubectl port-forward kuard-tls 8081:8443

apiVersion: v1
kind: Pod
metadata:
  name: kuard-tls
spec:
  containers:
    - name: kuard-tls
      image: gcr.io/kuar-demo/kuard-amd64:blue
      imagePullPolicy: Always
      volumeMounts:
        - name: tls-certs
          mountPath: "/tls"
          readOnly: true
  volumes:
    - name: tls-certs
      secret:
        secretName: kuard-tls
