apiVersion: v1
kind: Pod
metadata:
  name: s1-pod-demo-command-args
spec:
  containers:
    - name: debian
      image: debian:bullseye
      command: ["printenv"]
      args: ["HOSTNAME", "KUBERNETES_PORT"]
