apiVersion: v1
kind: Pod
metadata:
  name: s14-pod-dns-clusterfirstwithhostnet
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "1d"]
  hostNetwork: true
  dnsPolicy: 'ClusterFirstWithHostNet'
