# 2022-04-19 02:40:47 ⌚  zhulei-ccubuntu in ~/workspace/xxx-playground/k8s
# ± |main S:1 ?:3 ✗| → kubectl apply -f s14-pod-dns-none.yaml
# The Pod "s14-pod-dns-none" is invalid: spec.dnsConfig: Required value: must provide `dnsConfig` when `dnsPolicy` is None

apiVersion: v1
kind: Pod
metadata:
  name: s14-pod-dns-none
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "1d"]
  dnsPolicy: 'None'
  dnsConfig:
    nameservers: ["8.8.8.8"]
    searches: ["zhulei", "org.zhulei"]
    options:
      - name: ndots
        value: "2"
