apiVersion: v1
kind: Pod
metadata:
  name: s2-pod-demo-command-args-script-env
spec:
  containers:
  - name: debian
    image: debian:bullseye
    command: ['/bin/bash']
    env:
    - name: MESSAGE
      value: 'hello world'
    args: ['-c', 'i=0; while true; do echo "${i}: $(date) $(MESSAGE)"; i=$((i+1)); sleep 10;done']
