apiVersion: apps/v1
kind: Deployment
metadata:
  name: s22-deployment-strategy-rollingupdate
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: s22-deployment-strategy-rollingupdate
  template:
    metadata:
      labels:
        app: s22-deployment-strategy-rollingupdate
    spec:
      containers:
      - name: busybox
        image: busybox:1.28
        command:
        - sh
        - -c
        args:
        - |
          sleep 1d
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthz
          periodSeconds: 1
