apiVersion: v1
kind: Pod
metadata:
  name: s25-pod-liveness-probe-exec
spec:
  containers:
    - name: busybox
      image: busybox:1.28
      command: ["sh", "-c"]
      args:
      - |
        touch /tmp/healthz
        sleep 20
        rm /tmp/healthz
        sleep 2m
      livenessProbe: # 不支持修改
        exec:
          command:
          - cat
          - /tmp/healthz
        initialDelaySeconds: 3
        periodSeconds: 2
        timeoutSeconds: 2
        successThreshold: 1
        failureThreshold: 4
