apiVersion: v1
kind: Service
metadata:
  name: h3d-cluster-mysql-master
  labels:
    app: mysql
spec:
  ports:
  - name: tcp-mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      version: v1
  template:
    metadata:
      labels:
        app: mysql
        version: v1
    spec:
      initContainers:
      - name: download-sql
        image: busybox:1.28
        command:
        - wget
        - "-O"
        - "/initdb-dir/matchsrpg_trunk_all.sql"
        - http://nexus.h3d.com.cn/repository/tac/codecheck/matchsrpg_trunk_all.sql
        volumeMounts:
        - name: initdb-dir
          mountPath: "/initdb-dir"
      containers:
      - args:
        - --ignore-db-dir
        - lost+found
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "111111"
        - name: MYSQL_USER
          value: hardcore
        - name: MYSQL_PASSWORD
          value: "111111"
        - name: MYSQL_DATABASE
          value: dev_game
        - name: TZ
          value: Asia/Shanghai
        image: mysql:5.7
        name: mysql
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: initdb-dir
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: initdb-dir
        emptyDir: {}
      - name: data
        persistentVolumeClaim:
          claimName: mysql-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
