apiVersion: v1
kind: Pod
metadata:
  name: s32-pod-startup-delay
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
    - sh
    - -c
    args:
    - |
      sleep 10s
      touch /tmp/startup
      sleep 1d
    startupProbe:
      exec:
        command:
        - cat
        - /tmp/startup
      initialDelaySeconds: 3
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3

