apiVersion: v1
kind: Pod
metadata:
  generateName: s33-pod-podantiaffinity-
  labels:
    app: s33-pod-podAntiAffinity
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app: s33-pod-podAntiAffinity
  containers:
  - name: busybox
    image: busybox:1.28
    command:
    - sh
    - -c
    args:
    - |
      sleep 1d

