apiVersion: apps/v1
kind: Deployment
metadata:
  name: yireader
  labels:
    app.kubernetes.io/name: yireader
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: yireader
      app.kubernetes.io/component: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yireader
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: yireader
        image: uhziel/yireader
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: NODE_ENV
            value: production
          - name: SECRET_KEY
            value: Mwxyf3.gwDkMEf
          - name: MONGODB_URI
            value: mongodb://root:pZXswnYF#ch6iU@mongo:27017/yireader?authSource=admin&retryWrites=true&w=majority
        ports:
          - containerPort: 3001
