apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: golang-docker
build:
  artifacts:
    - image: hello
      docker:
        dockerfile: Dockerfile
  local:
    useDockerCLI: true
manifests:
  rawYaml:
    - k8s.yaml
