apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: deployment
  template:
    metadata:
      labels:
        app: deployment
    spec:
      restartPolicy: OnFailure
      containers:
      - name: busybox
        image: busybox
        command:
        - sleep
        args:
        - infinity
# The Deployment "deployment" is invalid: spec.template.spec.restartPolicy: Unsupported value: "OnFailure": supported values: "Always"
