apiVersion: v1
kind: Pod
metadata:
  name: 1-use-provisioner
  labels:
    name: 1-use-provisioner
spec:
  containers:
    - name: 1-use-provisioner
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: log-dir
  volumes:
    - name: log-dir
      persistentVolumeClaim:
        claimName: 1-use-provisioner
