apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: daemon-container-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: redis
        template: redis

    - - name: redis-cli
        template: redis-cli
        arguments:
          parameters:
          - name: cmd
            value: redis-cli -h {{steps.redis.ip}} PING

  - name: redis
    daemon: true
    retryStrategy:
      limit: 10
    container:
      image: registry.h3d.com.cn/tac/redis:6.2.6

  - name: redis-cli
    inputs:
      parameters:
      - name: cmd
    container:
      image: registry.h3d.com.cn/tac/redis:6.2.6
      command: ["/bin/sh", "-c"]
      args: ["{{inputs.parameters.cmd}}"]
