apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-1
spec:
  parallelism: 2
  completions: 8
  template:
    metadata:
      name: job-wq-1
    spec:
      containers:
      - name: consumers
        image: uhziel/job-wq-1
        env:
          - name: BROKER_URL
            value: amqp://guest:guest@rabbitmq-service:5672
          - name: QUEUE
            value: job2
      restartPolicy: OnFailure
