apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: app-data
      containers:
        - name: app
          image: grafana/tns-app:latest
          args:
            - "-log.level=debug"
            - "http://db"
          resources:
            limits:
              memory: "64Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /var/log
              name: app-data
          ports:
            - containerPort: 80
