apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: app-data
      containers:
        - name: app
          image: grafana/tns-app:latest
          command: # https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/
            - "/bin/sh"
          args:
            - "-c"
            - "/app -log.level=debug http://db:8082 > /var/log/tns-app.log"
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /var/log
              name: app-data
          ports:
            - containerPort: 80
