- name: Fix centos8 dnf
  hosts: codecc
  tasks:
  - name: Fix
    ansible.builtin.shell: |-
      if ! grep -r '#mirrorlist' /etc/yum.repos.d > /dev/null; then
        sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
      fi
