- name: Set nfs4_unique_id
  hosts: codecc
  tasks:
  - name: Install uuid
    ansible.builtin.dnf:
      name: uuid
      state: present
  - name: Set nfs4_unique_id to uuid
    ansible.builtin.shell: |-
      echo options nfs nfs4_unique_id=$(uuid) > /etc/modprobe.d/nfsclient.conf
    args:
      creates: /etc/modprobe.d/nfsclient.conf
    notify:
    - Reboot
  handlers:
  - name: Reboot
    ansible.builtin.reboot:
