# 我没试验下面的例子，看文档说非常，需要等待很长时间
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: jupyter
  name: jupyter
  namespace: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jupyter
  template:
    metadata:
      labels:
        run: jupyter
    spec:
      containers:
        - image: jupyter/scipy-notebook:abdb27a6dfbb
          name: jupyter
      dnsPolicy: ClusterFirst
      restartPolicy: Always
