#    Limits:
#      cpu:     1
#      memory:  256Mi
#    Requests:
#      cpu:        500m
#      memory:     128Mi
# 分配超过500MB内存后，确实会触发重启。通过 kubectl get pods 查看的 RESTARTS 次数
apiVersion: v1
kind: Pod
metadata:
  name: kuard-reslim
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:blue
      name: kuard
      resources:
        requests:
          cpu: "500m" # 0.5 cpu
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
  