apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            requests:
              cpu: "100m"
              memory: "70Mi"
            limits:
              cpu: "300m"
              memory: "200Mi"
          ports:
            - containerPort: 80
      #nodeSelector:
      #  kubernetes.io/hostname: rk3318-box

