apiVersion: batch/v1
kind: Job
metadata:
 name: job
spec:
 template:
   spec:
     restartPolicy: Never
     containers:
       - name: md5sum
         image: busybox
         command:
           - sh
           - -c
           - "echo hello | md5sum"
