apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
spec:
  selector:
    matchLabels:
      app: replicaset
  template:
    metadata:
      labels:
        app: replicaset
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - sleep
        args:
        - infinity
